

def create_tables(cursor):
	
	cursor.execute(
		'''

		DROP TABLE IF EXISTS vsapp."Users";

		CREATE TABLE IF NOT EXISTS vsapp."Users"
		(
		"Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
		"Username" character varying COLLATE pg_catalog."default" NOT NULL,
		"Password" character varying COLLATE pg_catalog."default" NOT NULL,
		"Email" character varying COLLATE pg_catalog."default" NOT NULL,
		"Role" smallint NOT NULL DEFAULT 0,
		CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
		)

		TABLESPACE pg_default;

		ALTER TABLE IF EXISTS vsapp."Users"
			OWNER to postgres;
		'''

	)


	cursor.execute(
		'''
		DROP TABLE IF EXISTS vsapp."Videos";

		CREATE TABLE IF NOT EXISTS vsapp."Videos"
		(
			"Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
			"VideoAddress" character varying COLLATE pg_catalog."default" NOT NULL,
			"IdUser" integer NOT NULL,
			"Duration" integer NOT NULL,
			"Height" integer NOT NULL,
			"Width" integer NOT NULL,
			"URL" character varying COLLATE pg_catalog."default",
			CONSTRAINT "Assets_pkey" PRIMARY KEY ("Id"),
			CONSTRAINT "Videos_IdUser_fkey" FOREIGN KEY ("IdUser")
				REFERENCES vsapp."Users" ("Id") MATCH SIMPLE
				ON UPDATE NO ACTION
				ON DELETE NO ACTION
				NOT VALID
		)

		TABLESPACE pg_default;

		ALTER TABLE IF EXISTS vsapp."Videos"
			OWNER to postgres;
		
		'''
	)

